version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: 'postgresql'
    environment:
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda
      POSTGRES_DB: camunda
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    container_name: 'rabbitmq'
    ports:
    - "5672:5672"
    - "15672:15672"