spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda:
  bpm:
    admin-user:
      id: your-admin-user
    authorization:
      enabled: true
    generic-properties:
      properties:
        generalResourceWhitelistPattern: ".+"

spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: yourClientId
            client-secret: yourClientSecret
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/custom
        provider:
          custom:
            issuer-uri: https://example.com/oauth2/default

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG