spring.datasource:
  url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa
spring.h2.console.enabled: false
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  job-execution:
      deployment-aware: true
  history-level: FULL
  authorization.enabled: true
  default-serialization-format: application/json

job:
  breaks: # these are schedule entries
    - 13:00,14:00
    - SATURDAY,00:00,23:59
    - SUNDAY,00:00,23:59
  schedule: # these are cron expressions for controlling the job executor itself
    shutdown: 0 0 3 * * *
    start: 0 0 5 * * *
  scheduler.paused: false

logging:
  level:
    ROOT: INFO
    com.camunda.consulting: DEBUG
    org.camunda.bpm.engine.impl.cmd: DEBUG