camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  authorization:
    enabled: false

logging:
  level:
    org.camunda: INFO
    com.camunda.example.oauth2: DEBUG

spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: # Azure AD tenant ID
        credential:
          client-id: # App Client ID
          client-secret: # App Client Secret
